# Generated by Django 3.2.4 on 2021-06-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerse', '0002_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducacional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fechaNac', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('nvledu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerse.niveleducacional')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerse.pais')),
            ],
        ),
    ]
