# Generated by Django 3.2.4 on 2021-06-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerse', '0005_alter_usuario_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.CharField(max_length=50),
        ),
    ]
